import { BaseProviderAdapter, ProviderGenerateOptions, ProviderGenerateResult } from "./baseAdapter";
import { GoogleGenAI } from "@google/genai";

export class GeminiAdapter extends BaseProviderAdapter {
  id = "gemini-primary";
  name = "Google Gemini 2.0 Flash";
  type = "gemini";
  envVar = "GEMINI_API_KEY";
  defaultModel = "gemini-2.0-flash";

  public async healthCheck(): Promise<boolean> {
    if (!this.isConfigured()) return false;
    try {
      const apiKey = process.env[this.envVar];
      if (!apiKey) return false;
      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: { headers: { 'User-Agent': 'aistudio-build' } }
      });
      const res = await ai.models.generateContent({
        model: this.defaultModel,
        contents: "ping"
      });
      return typeof res.text === 'string';
    } catch (e) {
      return false;
    }
  }

  public async generateContent(options: ProviderGenerateOptions): Promise<ProviderGenerateResult> {
    const apiKey = process.env[this.envVar];
    if (!apiKey) {
      throw new Error(`Environment variable ${this.envVar} is missing.`);
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: { headers: { 'User-Agent': 'aistudio-build' } }
    });

    const response = await ai.models.generateContent({
      model: this.defaultModel,
      contents: options.prompt,
      config: options.systemInstruction ? { systemInstruction: options.systemInstruction } : undefined
    });

    const text = response.text || "No response generated by Gemini.";
    const promptTokens = this.estimateTokens(options.prompt);
    const completionTokens = this.estimateTokens(text);
    const costUsd = (promptTokens / 1000 * 0.0001) + (completionTokens / 1000 * 0.0004);

    return {
      text,
      providerId: this.id,
      providerName: this.name,
      promptTokens,
      completionTokens,
      costUsd,
      modelUsed: this.defaultModel
    };
  }
}
