import { GoogleGenAI } from "@google/genai";
import { DatabaseService } from "./db";

/**
 * Service to interface with Google Gemini AI models
 */
export class CopilotService {
  /**
   * Generates response from Gemini based on user prompt
   */
  public static async generateCopilotResponse(prompt: string): Promise<string> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is missing from environment secrets.");
    }

    try {
      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: `You are the GURU-XD Terminal Copilot V2, an expert WhatsApp & Telegram bot core system assistant.
You help administrators create custom Node.js bot command scripts (such as fetchers, moderation filters, automation hooks), debug active error stack logs, or optimize daemon server settings.
When generating bot command handler logic, always output clean, functional, and secure JavaScript code in a standard Markdown code block:
\`\`\`javascript
module.exports = async (client, message, args) => {
  // logic here
};
\`\`\`
Answer in a helpful, concise, and highly professional terminal assistant tone.`
        }
      });

      return response.text || "No output generated by the intelligence engine.";
    } catch (err: any) {
      console.error("Gemini Copilot Service Error:", err);
      throw new Error(err.message || "Failed to communicate with hypervisor AI stream.");
    }
  }
}

/**
 * Bot Daemon Service to mimic active event listener loops and trigger live container logs
 */
export class BotDaemonService {
  /**
   * Generates some random simulated activities to write in the database logs periodically
   */
  public static generateSimulatedActivity() {
    const dbService = DatabaseService.getInstance();
    const db = dbService.read();
    
    const activeBots = db.bots.filter(b => b.status === "running");
    if (activeBots.length === 0) return;

    // Pick a random bot
    const bot = activeBots[Math.floor(Math.random() * activeBots.length)];
    
    const events = [
      { type: "info", tag: "GATEWAY", msg: "Successfully synchronized socket handshake with chat provider server." },
      { type: "success", tag: "HANDLER", msg: "Handled message update trigger [.alive] successfully in 45ms." },
      { type: "info", tag: "DB_STREAM", msg: "Flushed transient user message schemas into local storage." },
      { type: "warning", tag: "CONNECTION", msg: "Network jitter detected. Re-establishing secure duplex tunnel..." },
      { type: "success", tag: "GATEWAY", msg: "Socket tunnel connection stabilized. Retrying queued messages buffer." },
      { type: "info", tag: "COMPILER", msg: "Reloaded custom user scripts successfully without core service interruption." }
    ];

    const chosen = events[Math.floor(Math.random() * events.length)];
    dbService.addLog(chosen.type as any, `${bot.name.toUpperCase().replace(/\s+/g, "_")}/${chosen.tag}`, chosen.msg);
  }
}
